# NumPy Exercises

This notebook contains exercises demonstrating various NumPy operations including:
- Array operations
- Matrix operations
- Indexing and slicing
- Data types and array views

In [ ]:
import numpy as np

## Exercise 1: Basic Array and Matrix Operations

This exercise demonstrates:
- Basic array creation and operations
- Matrix operations (addition, multiplication, element-wise operations)
- Matrix indexing and slicing

In [5]:
import numpy as np


def ex1():
    # Basic array operations
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1,2,3,4,5])
    print(a)
    print(b)
    c = a + b
    d = a * 2
    e = a ** 2
    print(c)
    print(d)
    print(e)
    
    print("-"*50)
    print("Matrix operations")
    print("-"*50)
    
    # Matrix operations
    matrix_a = np.array([[1,2],[1,2]], ndmin=2)
    matrix_b = np.array([[-1,3], [4,-5]], ndmin=2)
    matrix_c = matrix_a + matrix_b
    print(matrix_a)
    print(matrix_b)
    print("matrix_c = matrix_a + matrix_b = \n" + str(matrix_c))
    
    matrix_d = matrix_a * matrix_b  # element-wise multiplication
    print("matrix_d = matrix_a * matrix_b = \n" + str(matrix_d))
    
    matrix_e = matrix_a ** 2  # element-wise square
    print("matrix_e = matrix_a ** 2 = \n" + str(matrix_e))
    
    matrix_f = matrix_a @ matrix_b  # matrix multiplication
    print("matrix_f = matrix_a @ matrix_b = \n" + str(matrix_f))
    
    print("-"*50)
    print("Matrix indexing operations")
    print("-"*50)
    
    # Matrix indexing
    print("matrix_a[0,0] = " + str(matrix_a[0,0]))
    print("matrix_a[0,1] = " + str(matrix_a[0,1]))
    print("matrix_a[1,0] = " + str(matrix_a[1,0]))
    print("matrix_a[1,1] = " + str(matrix_a[1,1]))
    
    print("-"*50)
    print("matrix_f[-1,-1] = " + str(matrix_f[-1,-1]))
    print("neg indexing: mat_b = " + str(matrix_b[-1, -1]) + ", " + str(matrix_b[1, 1]))
    print("mat_b[-1, -1] == mat_b[1, 1] is " + str(matrix_b[-1, -1] == matrix_b[1, 1]))
    
    print("-"*50)
    print("Matrix slicing")
    print("-"*50)
    
    # Matrix slicing examples
    print(str(matrix_b[-2:]))  # from index -2 to the end
    print(str(matrix_b[:-2]))  # from the beginning to index -2
    print(str(matrix_b[::-1]))  # reverse the matrix
    print(str(matrix_b[::-1, ::-1]))  # reverse the matrix and its elements
    print(str(matrix_b[1:2:1, 0:1:1]))  # specific slicing example
    
    print("-"*50)
    
    # Array slicing examples
    stam_arr = np.array([1,2,3,4,5,6,7,8,9])
    print(stam_arr[1:4:2])  # takes every 2nd element beginning from index 1 to index 4 not including index 4
    print(stam_arr[::2])  # takes every 2nd element beginning from the index 0 (the start of the array) till its end (index 9)

# Run the exercise
ex1()

[1 2 3 4 5]
[1 2 3 4 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
--------------------------------------------------
Matrix operations
--------------------------------------------------
[[1 2]
 [1 2]]
[[-1  3]
 [ 4 -5]]
matrix_c = matrix_a + matrix_b = 
[[ 0  5]
 [ 5 -3]]
matrix_d = matrix_a * matrix_b = 
[[ -1   6]
 [  4 -10]]
matrix_e = matrix_a ** 2 = 
[[1 4]
 [1 4]]
matrix_f = matrix_a @ matrix_b = 
[[ 7 -7]
 [ 7 -7]]
--------------------------------------------------
Matrix indexing operations
--------------------------------------------------
matrix_a[0,0] = 1
matrix_a[0,1] = 2
matrix_a[1,0] = 1
matrix_a[1,1] = 2
--------------------------------------------------
matrix_f[-1,-1] = -7
neg indexing: mat_b = -5, -5
mat_b[-1, -1] == mat_b[1, 1] is True
--------------------------------------------------
Matrix slicing
--------------------------------------------------
[[-1  3]
 [ 4 -5]]
[]
[[ 4 -5]
 [-1  3]]
[[-5  4]
 [ 3 -1]]
[[4]]
-------------------------------------------

## Exercise 2: Data Types and Array Views

This exercise demonstrates:
- Different data types in NumPy
- Type conversion
- Array views vs copies
- Understanding array ownership

In [4]:
import numpy as np


def ex2():
    print("-"*50)
    print("Data types")
    print("-"*50)
    
    # Different data types
    a = np.array([4234325324324432452,50,50124], dtype="f8")
    print(a.dtype)
    print(a)
    
    b = np.array([48,49,50], dtype="f")
    print(b.dtype)
    print(b)
    
    # Type conversion
    c = b.astype("c")
    print(c.dtype)
    c = b.astype("i")
    print(c)
    
    # Array copies vs views
    d = c.copy()
    d[0] = 100
    print(d)
    
    e = c.view()
    e[0] = 100
    print(e)
    print(c)
    
    # Check array ownership
    print(e.base)  # to show if the array owns its data or not if not it will be the original array None otherwise
    print(d.base)
    
    # Nested views
    f = e.view()
    f[0] = 101
    print(c)  # should change by f to 101
    print(f)
    print(f.base)
    
    # Copy from view
    g = e.copy()
    g[0] = 102
    print(g)
    print(g.base)    
    print(e)
    print(e.base)

# Run the exercise
ex2()

--------------------------------------------------
Data types
--------------------------------------------------
float64
[4.23432532e+18 5.00000000e+01 5.01240000e+04]
float32
[48. 49. 50.]
|S1
[48 49 50]
[100  49  50]
[100  49  50]
[100  49  50]
[100  49  50]
None
[101  49  50]
[101  49  50]
[101  49  50]
[102  49  50]
None
[101  49  50]
[101  49  50]


## Interactive Exploration

Feel free to experiment with the code above by modifying the arrays, data types, or operations!